name: Deploy cseatamdin
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Server
        #uses: actions/checkout@v2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/jnpro
            git pull
            composer update
            php artisan optimize:clear
            echo 'dah siappp' 
